services:

  postgres:
    image: postgres
    container_name: ms-postgres-db
    environment:
      POSTGRES_USER: berke
      POSTGRES_PASSWORD: pg-db-12
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: ms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: ms-mongo-db
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=berke
      - MONGO_INITDB_ROOT_PASSWORD=mng-db-12
    # optional
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    container_name: ms-mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=berke
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mng-db-12
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # additional configs
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=q
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://berke:mng-db-12@mongodb:27017/
    # optional
    depends_on:
      mongodb:
        condition: service_healthy

  maildev:
    image: maildev/maildev
    container_name: ms-mail-dev
    ports:
      - 1080:1080
      - 1025:1025 # SMTP Server

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
